/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package taller2

import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner
import scala.util.Random

@RunWith(classOf[JUnitRunner])
class ComparadorTest extends AnyFunSuite {
  val objInsertionSort = new InsertionSort()
  val objQuickSort = new QuickSort()
  val objComparar = new Comparar()


  test("Comparar listas tamaño 50") {
    val lst = (1 to 50).map(_ => Random.nextInt(10000)).toList
    val cmp = (a:Int, b:Int) => a < b
    val (l1, l2) = objComparar.comparar[Int](objInsertionSort.sort[Int](cmp), objQuickSort.sort[Int](cmp), lst)
    assert(l1 >= l2)
  }

  test("Comparar listas tamaño 1000") {
    val lst = (1 to 1000).map(_ => Random.nextInt(10000)).toList
    val cmp = (a:Int, b:Int) => a < b
    val (l1, l2) = objComparar.comparar[Int](objInsertionSort.sort[Int](cmp), objQuickSort.sort[Int](cmp), lst)
    assert(l1 <= l2)
  }
  

  test("Comparar listas tamaño 5000") {
    val lst = (1 to 5000).map(_ => Random.nextInt(10000)).toList
    val cmp = (a:Int, b:Int) => a < b
    val (l1, l2) = objComparar.comparar[Int](objInsertionSort.sort[Int](cmp), objQuickSort.sort[Int](cmp), lst)
    assert(l1 <= l2)
  }
 

  test("Comparar listas tamaño 7000") {
    val lst = (1 to 7000).map(_ => Random.nextInt(10000)).toList
    val cmp = (a:Int, b:Int) => a < b
    val (l1, l2) = objComparar.comparar[Int](objInsertionSort.sort[Int](cmp), objQuickSort.sort[Int](cmp), lst)
    assert(l1 <= l2)
  }
 

}
