/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package taller2

import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner
import scala.util.Random

@RunWith(classOf[JUnitRunner])
class InsertionSortTest extends AnyFunSuite {
  val objInsertionSort = new InsertionSort()
  
  test("Caso 1 Enteros función insert listas tamaño 100") {
    val cmp = (a: Int, b: Int) => a < b
    val lst = (1 to 100).map(_ => Random.nextInt(10000)).toList.sortWith(cmp)
    val x = Random.nextInt(10000)
    assert(objInsertionSort.insert(x, lst,  cmp)._0 === (x :: lst).sortWith((cmp)))
  }

  test("Caso 2 Enteros función insert listas tamaño 500") {
    
    val cmp = (a: Int, b: Int) => a < b
    val lst = (1 to 500).map(_ => Random.nextInt(10000)).toList.sortWith(cmp)
    val x = Random.nextInt(10000)
    assert(objInsertionSort.insert(x, lst,  cmp)._0 === (x :: lst).sortWith((cmp)))
  }

  test("Caso 3 Enteros función insert listas tamaño 1000") {
    
    val cmp = (a: Int, b: Int) => a < b
    val lst = (1 to 1000).map(_ => Random.nextInt(10000)).toList.sortWith(cmp)
    val x = Random.nextInt(10000)
    assert(objInsertionSort.insert(x, lst,  cmp)._0 === (x :: lst).sortWith((cmp)))
  }
}
