/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package taller2

import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner
import scala.util.Random

@RunWith(classOf[JUnitRunner])
class QuickSortTest extends AnyFunSuite {
  
  val objQuickSort = new QuickSort()
  
  test("Caso 1 Enteros función QuickSort listas tamaño 100") {
    val cmp = (a: Int, b: Int) => a < b
    val lst = (1 to 100).map(_ => Random.nextInt(10000)).toList.sortWith(cmp)
    assert(objQuickSort.sort[Int](cmp)(lst)._1 === lst.sortWith((cmp)))
  }

  test("Caso 2 Enteros función QuickSort listas tamaño 500") {
    
    val cmp = (a: Int, b: Int) => a < b
    val lst = (1 to 500).map(_ => Random.nextInt(10000)).toList.sortWith(cmp)
    assert(objQuickSort.sort[Int](cmp)(lst)._1 === lst.sortWith((cmp)))
  }

  test("Caso 3 Enteros función QuickSort listas tamaño 1000") {
    
    val cmp = (a: Int, b: Int) => a < b
    val lst = (1 to 1000).map(_ => Random.nextInt(10000)).toList.sortWith(cmp)
    assert(objQuickSort.sort[Int](cmp)(lst)._1 === lst.sortWith((cmp)))
  }
}
